### ISSUE TITLE
Huzzah ESP8266

### ISSUE THREAD

**Issue by bitoadpl** [G6EJD/ESP8266-METAR-Decoder-and-Display#1]
What is the proper wiring for Adafruit's Huzzah? There is no D0, D8, D7, D5 printings on board and (more important) no defined constants too.

**Comment by bitoadpl** [comment]
I have found solution myself. Here is proper wiring:

```
#define _CS 2 // GPIO 2
#define _DC 4 // GPIO 4
//#define _rst     // RST on ESP goes to TFT RESET 
//#define _miso    // GPIO 12
//        mosi     // GPIO 13
//        clk      // GPIO 14
//      v 3.3V    // Goes to TFT LED  
//      v 5v      // Goes to TFT Vcc
//      v Gnd     // Goes to TFT Gnd    
```

**Comment by G6EJD** [comment]
I thought Adafruit had mapped GPIO pins to the Dn nomenclature, obviously not. But you do this in the code.
