### ISSUE TITLE
Connection refused - Station Offline

### ISSUE THREAD

**Issue by fermintm** [G6EJD/ESP8266-METAR-Decoder-and-Display#3]
Hello!

Lately all the stations are Offline and apart from that it shows in the serial terminal the message Connection refused - Station Offline.
I don't know if it's an internet failure or that they have changed the method of decoding METAR data.

Thanks!

**Comment by G6EJD** [comment]
Have you tried the latest code versions I updated here?
They keep changing the security of access, but the code was working 2-weeks ago.

**Comment by fermintm** [comment]
Hello, yes, I have tried this updated code.  Today it gave an error in all airports, both American and Spanish.

**Comment by G6EJD** [comment]
In which case they have blocked access, it may be a temporary security measure to prevent the Russians from getting weather forecast data, that’s my guess.

**Comment by G6EJD** [comment]
I’ll check it out later too

**Comment by G6EJD** [comment]
I've tested the code and it's working perfectly.

**Comment by fermintm** [comment]
Wow.  It must be a problem with the M5Stack library.  
Sorry for the inconvenience.

**Comment by dandspach** [comment]
Same issue here...getting this error while monitoring serial connection

[HTTP] GET... failed, error: connection failed
Station off-air
